macos_arm64_dmg_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    REPO: https://github.com/biolab/orange3.git
    BUILD_BRANCH: master
    BUILD_COMMIT: 3.36.0
    APP: "/Applications/Orange3.app"

    PYTHON_VERSION: 3.9.12
    PIP_PREFER_BINARY: "1"
    ARCH: "arm64"
    ARCHFLAGS: "-arch arm64"
    PATH: /opt/homebrew/opt/python@3.10/libexec/bin:$PATH

  prerequisites_script:
    - brew install python@3.10
    - brew install create-dmg
    - mkdir dist/

  checkout_orange_script:
    - git clone -q $REPO
    - cd orange3
    - git fetch origin $BUILD_BRANCH
    - git checkout $BUILD_COMMIT

  build_installer_script:
    - cd orange3
    - PIP_ARGS=( --pip-arg={-r,../specs/macos/requirements-arm64.txt,Orange3==$BUILD_COMMIT} );
    - ../scripts/macos/build-macos-app.sh --macos 11 "${PIP_ARGS[@]}" --python-version=${PYTHON_VERSION} "$APP"

  build_dmg_installer_script:
    - cd orange3
    - ../scripts/macos/create-dmg-installer.sh --app "$APP" dist/Orange3.dmg
    - >-
      VERSION=`$APP/Contents/MacOS/pip show orange3 | grep -E '^Version: ' | cut -d ' ' -f 2`
    - mv dist/Orange3.dmg dist/Orange3-$VERSION-Python${PYTHON_VERSION}-${ARCH}.dmg
    - shasum -a 256 dist/Orange3-$VERSION-Python${PYTHON_VERSION}-${ARCH}.dmg
    - mv dist/Orange3-$VERSION-Python${PYTHON_VERSION}-${ARCH}.dmg ../dist

  test_script:
    - mkdir -p ~/Applications
    - mv -f $APP ~/Applications/
    - APP=( ~/Applications/Orange3.app )
    - $APP/Contents/MacOS/python --version
    - $APP/Contents/MacOS/pip --version
    - $APP/Contents/MacOS/pip freeze
    - $APP/Contents/MacOS/python -Xfaulthandler -m unittest -v Orange.tests Orange.widgets.tests || true

  dmg_artifacts:
    path: "dist/*"